/* eslint-disable no-unused-vars */
/* eslint-disable react/no-unknown-property */
/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: hamdanbasri (https://sketchfab.com/hamdanbasri)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/claw-machine-3cfee69c4018495ebff080f055be28be
Title: Claw Machine
*/

import React, { useEffect, useMemo, useRef } from "react"
import { useGLTF } from "@react-three/drei"
import { useTexture } from "@react-three/drei"
import { DoubleSide, MeshPhysicalMaterial, MeshStandardMaterial } from "three"
import * as THREE from "three"

export function Floor(props) {
  const { nodes, materials } = useGLTF("/models/claw_machine.glb")

  const floorMaterial = new THREE.MeshStandardMaterial({
    color: 0x111111,
    roughness: 1,
    metalness: 0.01,
    envMapIntensity: 1,
    side: DoubleSide,
  })

  return (
    <group {...props} dispose={null}>
      <group scale={1}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.SM_Room_M_Floor_0.geometry}
          material={floorMaterial}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={[10, 10, 100]}
        />
      </group>
    </group>
  )
}

useGLTF.preload("/models/claw_machine.glb")
